python main.py -config config/config_MR_superposition.ini
python main.py -config config/config_CR_superposition.ini
python main.py -config config/config_SST_2_superposition.ini
python main.py -config config/config_SST_5_superposition.ini
python main.py -config config/config_TREC_superposition.ini
python main.py -config config/config_MPQA_superposition.ini
python main.py -config config/config_SUBJ_superposition.ini
python main.py -config config/config_MR_mixture.ini
python main.py -config config/config_CR_mixture.ini
python main.py -config config/config_SST_2_mixture.ini
python main.py -config config/config_SST_5_mixture.ini
python main.py -config config/config_TREC_mixture.ini
python main.py -config config/config_MPQA_mixture.ini
python main.py -config config/config_SUBJ_mixture.ini
python main.py -config config/config_MR_real.ini
python main.py -config config/config_CR_real.ini
python main.py -config config/config_SST_2_real.ini
python main.py -config config/config_SST_5_real.ini
python main.py -config config/config_TREC_real.ini
python main.py -config config/config_MPQA_real.ini
python main.py -config config/config_SUBJ_real.ini
